package com.glw.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table baseinfo_appeal
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class BaseinfoAppeal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_appeal.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_appeal.student_id
     *
     * @mbg.generated
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_appeal.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     * Database Column Remarks:
     *   1 基本信息申诉 2 成绩申诉 3 学分申诉
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_appeal.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_appeal.time
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd")
    private Date time;

    /**
     * Database Column Remarks:
     *   1 已处理 2 未处理
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baseinfo_appeal.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_appeal.id
     *
     * @return the value of baseinfo_appeal.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_appeal.id
     *
     * @param id the value for baseinfo_appeal.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_appeal.student_id
     *
     * @return the value of baseinfo_appeal.student_id
     *
     * @mbg.generated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_appeal.student_id
     *
     * @param studentId the value for baseinfo_appeal.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_appeal.desc
     *
     * @return the value of baseinfo_appeal.desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_appeal.desc
     *
     * @param desc the value for baseinfo_appeal.desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_appeal.type
     *
     * @return the value of baseinfo_appeal.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_appeal.type
     *
     * @param type the value for baseinfo_appeal.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_appeal.time
     *
     * @return the value of baseinfo_appeal.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_appeal.time
     *
     * @param time the value for baseinfo_appeal.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baseinfo_appeal.status
     *
     * @return the value of baseinfo_appeal.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baseinfo_appeal.status
     *
     * @param status the value for baseinfo_appeal.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}