package com.glw.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table course_credit
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CourseCredit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_credit.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_credit.student_id
     *
     * @mbg.generated
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_credit.course_id
     *
     * @mbg.generated
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_credit.course_name
     *
     * @mbg.generated
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_credit.credit
     *
     * @mbg.generated
     */
    private Double credit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_credit.id
     *
     * @return the value of course_credit.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_credit.id
     *
     * @param id the value for course_credit.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_credit.student_id
     *
     * @return the value of course_credit.student_id
     *
     * @mbg.generated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_credit.student_id
     *
     * @param studentId the value for course_credit.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_credit.course_id
     *
     * @return the value of course_credit.course_id
     *
     * @mbg.generated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_credit.course_id
     *
     * @param courseId the value for course_credit.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_credit.course_name
     *
     * @return the value of course_credit.course_name
     *
     * @mbg.generated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_credit.course_name
     *
     * @param courseName the value for course_credit.course_name
     *
     * @mbg.generated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_credit.credit
     *
     * @return the value of course_credit.credit
     *
     * @mbg.generated
     */
    public Double getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_credit.credit
     *
     * @param credit the value for course_credit.credit
     *
     * @mbg.generated
     */
    public void setCredit(Double credit) {
        this.credit = credit;
    }
}