package com.glw.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table my_course
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class MyCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_course.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_course.student_id
     *
     * @mbg.generated
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_course.course_id
     *
     * @mbg.generated
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_course.course_name
     *
     * @mbg.generated
     */
    private String courseName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_course.id
     *
     * @return the value of my_course.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_course.id
     *
     * @param id the value for my_course.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_course.student_id
     *
     * @return the value of my_course.student_id
     *
     * @mbg.generated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_course.student_id
     *
     * @param studentId the value for my_course.student_id
     *
     * @mbg.generated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_course.course_id
     *
     * @return the value of my_course.course_id
     *
     * @mbg.generated
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_course.course_id
     *
     * @param courseId the value for my_course.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_course.course_name
     *
     * @return the value of my_course.course_name
     *
     * @mbg.generated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_course.course_name
     *
     * @param courseName the value for my_course.course_name
     *
     * @mbg.generated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }
}