package com.glw.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table student_baseinfo
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class StudentBaseinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_baseinfo.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_baseinfo.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_baseinfo.id_card
     *
     * @mbg.generated
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_baseinfo.gender
     *
     * @mbg.generated
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_baseinfo.native_place
     *
     * @mbg.generated
     */
    private String nativePlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_baseinfo.birth
     *
     * @mbg.generated
     */
    private Date birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_baseinfo.major
     *
     * @mbg.generated
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_baseinfo.come_time
     *
     * @mbg.generated
     */
    private Date comeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_baseinfo.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_baseinfo.second_phone
     *
     * @mbg.generated
     */
    private String secondPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_baseinfo.qq
     *
     * @mbg.generated
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_baseinfo.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_baseinfo.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_baseinfo.id
     *
     * @return the value of student_baseinfo.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_baseinfo.id
     *
     * @param id the value for student_baseinfo.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_baseinfo.name
     *
     * @return the value of student_baseinfo.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_baseinfo.name
     *
     * @param name the value for student_baseinfo.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_baseinfo.id_card
     *
     * @return the value of student_baseinfo.id_card
     *
     * @mbg.generated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_baseinfo.id_card
     *
     * @param idCard the value for student_baseinfo.id_card
     *
     * @mbg.generated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_baseinfo.gender
     *
     * @return the value of student_baseinfo.gender
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_baseinfo.gender
     *
     * @param gender the value for student_baseinfo.gender
     *
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_baseinfo.native_place
     *
     * @return the value of student_baseinfo.native_place
     *
     * @mbg.generated
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_baseinfo.native_place
     *
     * @param nativePlace the value for student_baseinfo.native_place
     *
     * @mbg.generated
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_baseinfo.birth
     *
     * @return the value of student_baseinfo.birth
     *
     * @mbg.generated
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_baseinfo.birth
     *
     * @param birth the value for student_baseinfo.birth
     *
     * @mbg.generated
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_baseinfo.major
     *
     * @return the value of student_baseinfo.major
     *
     * @mbg.generated
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_baseinfo.major
     *
     * @param major the value for student_baseinfo.major
     *
     * @mbg.generated
     */
    public void setMajor(String major) {
        this.major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_baseinfo.come_time
     *
     * @return the value of student_baseinfo.come_time
     *
     * @mbg.generated
     */
    public Date getComeTime() {
        return comeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_baseinfo.come_time
     *
     * @param comeTime the value for student_baseinfo.come_time
     *
     * @mbg.generated
     */
    public void setComeTime(Date comeTime) {
        this.comeTime = comeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_baseinfo.phone
     *
     * @return the value of student_baseinfo.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_baseinfo.phone
     *
     * @param phone the value for student_baseinfo.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_baseinfo.second_phone
     *
     * @return the value of student_baseinfo.second_phone
     *
     * @mbg.generated
     */
    public String getSecondPhone() {
        return secondPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_baseinfo.second_phone
     *
     * @param secondPhone the value for student_baseinfo.second_phone
     *
     * @mbg.generated
     */
    public void setSecondPhone(String secondPhone) {
        this.secondPhone = secondPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_baseinfo.qq
     *
     * @return the value of student_baseinfo.qq
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_baseinfo.qq
     *
     * @param qq the value for student_baseinfo.qq
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_baseinfo.email
     *
     * @return the value of student_baseinfo.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_baseinfo.email
     *
     * @param email the value for student_baseinfo.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_baseinfo.location
     *
     * @return the value of student_baseinfo.location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_baseinfo.location
     *
     * @param location the value for student_baseinfo.location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location;
    }
}