package com.glw.dao;

import com.glw.model.BaseinfoAppeal;

public interface BaseinfoAppealMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_appeal
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_appeal
     *
     * @mbg.generated
     */
    int insert(BaseinfoAppeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_appeal
     *
     * @mbg.generated
     */
    int insertSelective(BaseinfoAppeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_appeal
     *
     * @mbg.generated
     */
    BaseinfoAppeal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_appeal
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BaseinfoAppeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baseinfo_appeal
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BaseinfoAppeal record);
}