package com.glw.dao;

import com.glw.model.CourseTest;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CourseTestMapper {

    /**
     * @Description: 根据课程ID查询课程考试信息
     * @MethodName: listCourseTestByCourseId
     * @Parameter:
     * @Return:
     * @author: GaoLiWei
     * @email: 1121581012@qq.com
     * @date 2018/3/30 15:33
     * @version V1.0
     */
    List<CourseTest> listCourseTestByCourseId (@Param("courseId") Integer courseId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_test
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_test
     *
     * @mbg.generated
     */
    int insert(CourseTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_test
     *
     * @mbg.generated
     */
    int insertSelective(CourseTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_test
     *
     * @mbg.generated
     */
    CourseTest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_test
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CourseTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_test
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CourseTest record);
}