package com.glw.dao;

import com.glw.model.CreditAppeal;

public interface CreditAppealMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_appeal
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_appeal
     *
     * @mbg.generated
     */
    int insert(CreditAppeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_appeal
     *
     * @mbg.generated
     */
    int insertSelective(CreditAppeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_appeal
     *
     * @mbg.generated
     */
    CreditAppeal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_appeal
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CreditAppeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table credit_appeal
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CreditAppeal record);
}