package com.glw.dao;

import com.glw.model.Course;
import com.glw.model.MyCourse;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MyCourseMapper {

    /**
     * @Description:  根据学生ID，课程ID 删除我的选课
     * @MethodName: deleteMyCourseByCourseIdAndeStudentId
     * @Parameter: Integer studentId, Integer courseId
     * @Return:
     * @author: GaoLiWei
     * @email: 1121581012@qq.com
     * @date 2018/4/2 22:40
     * @version V1.0
     */
    int deleteMyCourseByCourseIdAndeStudentId(@Param("studentId") Integer studentId, @Param("courseId") Integer courseId);

    /**
     * @Description: 根据学生ID，课程ID查看学生是否已经选了这门课
     * @MethodName: listMyCourseByStudentIdAndCourseId
     * @Parameter:
     * @Return: List<MyCourse>
     * @author: GaoLiWei
     * @email: 1121581012@qq.com
     * @date 2018/3/30 14:56
     * @version V1.0
     */
    List<MyCourse> listMyCourseByStudentIdAndCourseId(@Param("studentId") Integer studentId, @Param("courseId") Integer courseId);

    /**
     * @description: 根据学生ID查询该学生选择的课程
     * @MethodName: listCourseByStudentId
     * @Parameter: Integer studentId
     * @Return: List<Course>
     * @author: GaoLiWei
     * @email: 1121581012@qq.com
     * @date 2018/4/2 22:17
     * @version V1.0
     */
    List<Course> listCourseByStudentId(@Param("studentId") Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_course
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_course
     *
     * @mbg.generated
     */
    int insert(MyCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_course
     *
     * @mbg.generated
     */
    int insertSelective(MyCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_course
     *
     * @mbg.generated
     */
    MyCourse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MyCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MyCourse record);
}