package com.glw.dao;

import com.glw.model.MyCourse;

public interface MyCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_course
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_course
     *
     * @mbg.generated
     */
    int insert(MyCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_course
     *
     * @mbg.generated
     */
    int insertSelective(MyCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_course
     *
     * @mbg.generated
     */
    MyCourse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MyCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MyCourse record);
}