package com.glw.dao;

import com.glw.model.MyScore;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MyScoreMapper {

    /**
     * @Description: 根据学生ID查询该学生的分数
     * @MethodName: listMyScoreByStudentId
     * @Parameter:
     * @Return:
     * @author: GaoLiWei
     * @email: 1121581012@qq.com
     * @date 2018/4/3 17:31
     * @version V1.0
     */
    List<MyScore> listMyScoreByStudentId(@Param("studentId") Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_score
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_score
     *
     * @mbg.generated
     */
    int insert(MyScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_score
     *
     * @mbg.generated
     */
    int insertSelective(MyScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_score
     *
     * @mbg.generated
     */
    MyScore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MyScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_score
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MyScore record);
}