package com.glw.dao;

import com.glw.model.StudentBaseinfo;

public interface StudentBaseinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_baseinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_baseinfo
     *
     * @mbg.generated
     */
    int insert(StudentBaseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_baseinfo
     *
     * @mbg.generated
     */
    int insertSelective(StudentBaseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_baseinfo
     *
     * @mbg.generated
     */
    StudentBaseinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_baseinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StudentBaseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_baseinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StudentBaseinfo record);
}